server:
  port: 7000



resilience4j:
  circuitbreaker:
    instances:
      productService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 5
management:
  endpoints:
    web:
      exposure:
        include: resilience4j.circuitbreaker, health, info